lug: add lean4 pkgs
sjtug/mirror-docker-unified pull request #428
Opened 2023-10-01 18:07 UTC by alissa-tung

I am not sure whether I can use second level paths. If that can work as a namespace I think this would be better...

2023-10-01 20:43 UTC, PhotonQuantum requested changes
Don't forget to run `make caddy-gen` after modifications.

2023-10-01 20:43 UTC, PhotonQuantum commented on config.siyuan.yaml
> +    target: https://git.sjtu.edu.cn/sjtug/lean4-packages/std4.git
`git.sjtu.edu.cn` is another server hosted by NIC. We don't need it anymore, so you can just remove this line.

2023-10-01 20:43 UTC, PhotonQuantum commented on config.siyuan.yaml
> +    path: /srv/data32T/git/lean4-packages/std4
Path must end with `.git` because it's a bare repo.

2023-10-02 04:06 UTC, PhotonQuantum approved these changes
Looks good! Please rebase it onto the main branch.

2023-10-02 04:09 UTC, alissa-tung commented
> Looks good! Please rebase it onto the main branch.

fixed. thank u

2023-10-02 04:19 UTC, merged

2023-10-02 04:21 UTC, PhotonQuantum commented
Would you be willing to provide a guide on how to use this mirror? https://github.com/sjtug/portal

2023-10-02 04:22 UTC, alissa-tung commented
> Would you be willing to provide a guide on how to use this mirror? https://github.com/sjtug/portal

Yes. I am writing one